services:
    # First Spring Boot Uygulamas覺
    first-backend:
        build:
            context: ../../../first
            dockerfile: Dockerfile
        container_name: first-backend
        ports:
            - "8080:80"
        networks:
            - app-network
        restart: unless-stopped

    # Second Spring Boot Uygulamas覺
    second-backend:
        build:
            context: ../../../second
            dockerfile: Dockerfile
        container_name: second-backend
        ports:
            - "9090:80"
        networks:
            - app-network
        restart: unless-stopped

    # First React Uygulamas覺
    first-frontend:
        build:
            context: ../../../first-app-frontend
            dockerfile: ${DOCKERFILE:-Dockerfile.prod}
        container_name: first-frontend
        ports:
            - "3000:80"
        depends_on:
            - first-backend
        networks:
            - app-network
        restart: unless-stopped

    # Second React Uygulamas覺
    second-frontend:
        build:
            context: ../../../second-app-frontend
            dockerfile: ${DOCKERFILE:-Dockerfile.prod}
        container_name: second-frontend
        ports:
            - "4000:80"
        depends_on:
            - second-backend
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge